import BlurredText from 'components/animation/BlurredText'
import Intro from 'components/animation/Intro'
import HomeAbout from 'components/core/HomeAbout'
import ObjectiveContent from 'components/core/ObjectiveContent'
import ObjectiveContentRight from 'components/core/ObjectiveContentRight'
import FooterClass from 'components/core/FooterClass'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './index.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <HomeAbout />
      <ObjectiveContent text=" Aplicar el Marco Decenal de Programas sobre Modalidades de Consumo y 
            Producción Sostenibles, con la participación de todos los países y bajo 
            el liderazgo de los países desarrollados, teniendo en cuenta el grado de 
            desarrollo y las capacidades de los países en desarrollo.
          " image="https://unsplash.it/400" />
      <ObjectiveContentRight text=" De aquí a 2030, lograr la gestión sostenible y el uso eficiente de los 
            recursos naturales." image="https://unsplash.it/401"/>
      <ObjectiveContent text=" De aquí a 2030, reducir a la mitad el desperdicio de alimentos per capita 
            mundial en la venta al por menor y a nivel de los consumidores y reducir 
            las pérdidas de alimentos en las cadenas de producción y suministro, incluidas 
            las pérdidas posteriores a la cosecha." image="https://unsplash.it/400" />
      <ObjectiveContentRight text="  De aquí a 2020, lograr la gestión ecológicamente racional de los productos químicos 
            y de todos los desechos a lo largo de su ciclo de vida, de conformidad con los marcos
             internacionales convenidos, y reducir significativamente su liberación a la atmósfera, 
             el agua y el suelo a fin de minimizar sus efectos adversos en la salud humana y el medio 
             ambiente." image="https://unsplash.it/401"/>
       <ObjectiveContent text="   De aquí a 2030, reducir considerablemente la generación de desechos 
            mediante actividades de prevención, reducción, reciclado y reutilización.
          " image="https://unsplash.it/400" />
      <ObjectiveContentRight text="Alentar a las empresas, en especial las grandes empresas y las empresas 
            transnacionales, a que adopten prácticas sostenibles e incorporen información 
            sobre la sostenibilidad en su ciclo de presentación de informes.
          " image="https://unsplash.it/401"/>
      <ObjectiveContent text=" Promover prácticas de adquisición pública que sean sostenibles, de conformidad 
                con las políticas y prioridades nacionales." image="https://unsplash.it/400" />
      <ObjectiveContentRight text="  De aquí a 2030, asegurar que las personas de todo el mundo tengan la información y 
            los conocimientos pertinentes para el desarrollo sostenible y los estilos de vida 
            en armonía con la naturaleza." image="https://unsplash.it/401"/>
      <ObjectiveContent text=" Ayudar a los países en desarrollo a fortalecer su capacidad científica y tecnológica 
            para avanzar hacia modalidades de consumo y producción más sostenibles." image="https://unsplash.it/400" />
      <ObjectiveContentRight text=" Elaborar y aplicar instrumentos para vigilar los efectos en el desarrollo sostenible, a fin 
        de lograr un turismo sostenible que cree puestos de trabajo y promueva la cultura y los productos locales." image="https://unsplash.it/401"/>
      <ObjectiveContent text=" Racionalizar los subsidios ineficientes a los combustibles fósiles que fomentan el consumo antieconómico eliminando 
        las distorsiones del mercado, de acuerdo con las circunstancias nacionales, incluso mediante la reestructuración de 
        los sistemas tributarios y la eliminación gradual de los subsidios perjudiciales, cuando existan, para reflejar su 
        impacto ambiental, teniendo plenamente en cuenta las necesidades y condiciones específicas de los países en desarrollo
         y minimizando los posibles efectos adversos en su desarrollo, de manera que se proteja a los pobres y a las comunidades afectadas." image="https://unsplash.it/400" />
    </div>
  )
}

export default Home
