import Button from 'components/core/Button'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './index.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bar}>
        <Button />
      </div>

    </div>
  )
}

export default Home
